services:
  api:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      target: api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  consumer:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      target: consumer
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    container_name: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/18/data

  rabbit:
    image: rabbitmq@sha256:0753b75ce99094c385483d89449d532a0544fb85e4942a478b21cc497ab66d33
    container_name: rabbit
    restart: always
    ports:
      - "${RABBIT_PORT}:15672" # Do not change order of ports, it is important
      - "${AMQP_PORT}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s

  redis:
    image: redis@sha256:2838d5524559494f6f1cd66e97e76b200d64a633a8614200620755ed395daf32
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
