"""Initial migration

Revision ID: b7ff5d54ca90
Revises:
Create Date: 2026-07-19 22:26:31.335663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7ff5d54ca90"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column(
            "category_name",
            sa.Enum("CLOTHES", "ELECTRONICS", "MISC", name="categoryenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "packages",
        sa.Column("uid", sa.String(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("dollar_price", sa.Float(), nullable=False),
        sa.Column("delivery_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_packages_session_id"), "packages", ["session_id"], unique=False
    )
    # ### end Alembic commands ###
    conn = op.get_bind()
    query = sa.text("SELECT uid FROM categories LIMIT 1")
    res = conn.execute(query)
    if res.first():
        return

    meta = sa.MetaData()

    ctg_table = sa.Table("categories", meta, autoload_with=conn)

    op.bulk_insert(
        ctg_table,
        [
            {"category_name": "CLOTHES"},
            {"category_name": "ELECTRONICS"},
            {"category_name": "MISC"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packages_session_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_table("categories")
    # ### end Alembic commands ###
