FROM astral/uv:python3.14-trixie-slim@sha256:b6e3a8825dfb232a6b962228f0b5cf98ee1d2b4263f62c2639f68887f4e634a2 AS base
WORKDIR /app
COPY pyproject.toml  pyproject.toml

ENV PYTHONUNBUFFERED=1

COPY packages/ packages/
RUN uv pip install --system -e packages/shared

FROM base AS api-gateway
COPY src/api-gateway src/api-gateway/
RUN uv pip install --system -e src/api-gateway
ENTRYPOINT ["uvicorn", "--app-dir", "src/api-gateway/src", "main:app", "--host", "0.0.0.0"]

FROM base AS mq-consumer
COPY src/mq-consumer src/mq-consumer/
RUN uv pip install --system -e src/mq-consumer
ENTRYPOINT ["uvicorn", "--app-dir", "src/mq-consumer/src", "main:app", "--host", "0.0.0.0"]





