FROM astral/uv:python3.14-trixie-slim@sha256:b6e3a8825dfb232a6b962228f0b5cf98ee1d2b4263f62c2639f68887f4e634a2 AS base
WORKDIR /app
COPY pyproject.toml  pyproject.toml

ENV PYTHONUNBUFFERED=1

COPY packages/ packages/
RUN uv pip install --system -e packages/shared

FROM base AS api_gateway
COPY src/api_gateway src/api_gateway/
RUN uv pip install --system -e src/api_gateway
ENTRYPOINT ["uvicorn", "--app-dir", "src/api_gateway/src", "main:app", "--host", "0.0.0.0"]

FROM base AS mq_consumer
COPY src/mq_consumer src/mq_consumer/
RUN uv pip install --system -e src/mq_consumer
ENTRYPOINT ["uvicorn", "--app-dir", "src/mq_consumer/src", "main:app", "--host", "0.0.0.0"]





