"""Initial migration

Revision ID: d2935b39852f
Revises: 
Create Date: 2026-07-11 15:57:40.202313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2935b39852f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.Enum('CLOTHES', 'ELECTRONICS', 'MISC', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('packages',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('dollar_price', sa.Float(), nullable=False),
    sa.Column('ruble_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    op.drop_table('categories')
    # ### end Alembic commands ###
